version: "3.9"
services:
  server:
    build: 
      context: .
      dockerfile: ./FridgeApp.Api/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local